- hosts: localhost
  become: false 
  tasks:
    - name: Install Tmux 
      homebrew: 
        name: tmux 
        state: present
      tags: 
        - tools
#   - name: Install Alacritty 
#     homebrew: 
#       name: alacritty 
#       state: present
#     tags: 
#       - tools
    - name: Install ohmyzsh 
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      tags: 
        - tools
